### ISSUE TITLE
kevent: No such process

### ISSUE THREAD

**Issue by OmeGak** [drinchev/phook#7] opened 2017-05-31 11:25 UTC
I just installed `phook` in a new machine and I'm getting this:

```console
$ phook -e 'echo marco' -a 'echo polo'
marco
kevent: No such process
```

Any idea what's wrong with it?

**Comment by drinchev** [comment] 2017-05-31 12:31
Hmm..

Actually `phook` should not output anything, except `Marco`, since there ( probably ) is no parent process. Anyway I'm a bit worried about `kevent: No such process`, so

Can you clone the repo, build and then execute

```
$ cd examples 
$./shell.sh
```

Then paste the output?

**Comment by OmeGak** [comment] 2017-05-31 13:32
Seems to be working fine when I compile it from source. 

```console
$ ./shell.sh
1
2
3
4
```

If I modify `shell.sh` to use the one I stalled from `brew` I get this:

```console
$ ./shell.sh
1
2
kevent: No such process
3
```

**Comment by drinchev** [comment] 2017-05-31 13:55
Can you confirm, your brew version `$ phook --version`

**Comment by OmeGak** [comment] 2017-05-31 16:04
```console
$ phook --version
phook 0.06
```

**Comment by drinchev** [comment] 2017-07-12 09:33
Hey there, do you still have this issue? It seems that I can't find a way to reproduce it.

**Comment by OmeGak** [comment] 2017-07-12 17:22
Yes. I reinstalled everything again from a clean system and keeps happening every single time.

**Comment by krschmidt** [comment] 2017-10-11 16:46
Having the same issue, only when installed from Homebrew. Also, -e seemed to work, but -a did not. Running High Sierra.

**Comment by drinchev** [comment] 2017-12-28 20:33
The problem seems that by default `home-brew` adds `-Os` flag to the compiler. 

In our case this optimisation ( no idea why ) creates a broken binary. I updated the Makefile and released v 0.0.7 with the proper flag.

Only thing left is @TheFox to update the repo and we are good to go ( I think ). Will keep this open until then. 

Merry Christmas!

**Comment by TheFox** [comment] 2017-12-29 08:43
@drinchev I updated the homebrew repo. See TheFox/homebrew-brewery@d3f0837a0d9655f0be009c3c1672f8ffaf75015a commit.

**Comment by martinlau** [comment] 2017-12-29 09:01
@TheFox @drinchev no change:


```shell
Martins-MacBook-Pro phook-0.0.7/examples » phook --version     
phook 0.07
Copyright (C) 2017 Ivan Drinchev
This software may be modified and distributed
under the terms of the MIT license.

Martins-MacBook-Pro phook-0.0.7/examples » ls -l $(which phook)
lrwxr-xr-x  1 martinlau  admin  31 29 Dec 19:57 /usr/local/bin/phook -> ../Cellar/phook/0.0.7/bin/phook

Martins-MacBook-Pro phook-0.0.7/examples » cat shell.sh 
#!/bin/bash

#
# Will output :
#
# 1
# 2
# 3
# 4
#

echo 1
phook -e 'echo 2' -a 'echo 4'
sleep 1
echo 3
exit 0

Martins-MacBook-Pro phook-0.0.7/examples » ./shell.sh 
1
2
kevent: No such process
3

```

**Comment by TheFox** [comment] 2017-12-29 09:57
Maybe Homebrew uses its own arguments to build it? Have you tried to manually build it?

**Comment by martinlau** [comment] 2017-12-29 10:36
Yeah - building from source works as expected.

You can use something like `brew install phook --keep-tmp --debug --verbose --interactive` to get a shell mid-build, which gives:

```
Martins-MacBook-Pro phook-20171229-54518-uht31g/phook-0.0.7 » set|grep -i optimization                                                                                                                                                      1 ↵
HOMEBREW_OPTIMIZATION_LEVEL=Os
```

A bit of googling for HOMEBREW_OPTIMIZATION_LEVEL:

https://github.com/Homebrew/legacy-homebrew/issues/45033 - references: https://github.com/Homebrew/legacy-homebrew/blob/bf3864c276049332f984acfdbee2602122813f24/Library/Formula/clisp.rb#L29 as an example. In particular:

```
  def install
    ENV.O0 # Any optimization breaks the build
```

**Comment by martinlau** [comment] 2017-12-29 10:38
FWIW, testing the above with `brew edit phook` and the formula:

```ruby

class Phook < Formula
  desc "Runs commands around a parent process"
  homepage "https://github.com/drinchev/phook"
  url "https://github.com/drinchev/phook/archive/v0.0.7.tar.gz"
  sha256 "c182948287c5a8f05cd6b7d1493caade0a0f4f8bb3cbaa82cd9d5527566a2ab0"

  depends_on "make" => :build

  def install
    ENV.O0 # Any optimization breaks the build
    system "make"

    bin.install "phook"
  end

  test do
    system "which", "-a", "phook"
  end
end

```

Works as expected.

**Comment by TheFox** [comment] 2017-12-29 10:41
Of course I can add this to the homebrew Formula, but I don't get it, why is it even necessary to compile it with `-O0`. Optimization is for the good. And `system "make"` means run `make` from this directory, right? Or I'm missing something?

**Comment by martinlau** [comment] 2017-12-29 10:43
Not sure - take a look at the environment when that shell spawns - there's MAKEOPTS, etc etc - so just running "make install" there isn't the same as running it natively under your own shell (unless you happen to have a bizarre .profile).

There are also some homebrew shims for things like "make" and "gcc" via the 'super env' under /usr/local/Homebrew/Library/Homebrew/shims/super

**Comment by TheFox** [comment] 2017-12-29 10:51
@martinlau  Please try it again. I updated the Formula.

**Comment by martinlau** [comment] 2017-12-29 10:53
@TheFox seems to work now.

:thumbsup:

**Comment by OmeGak** [comment] 2017-12-30 14:46
Working like a charm now. Thanks!

**Comment by drinchev** [comment] 2019-03-13 18:37
Can I close this, btw?

**Comment by OmeGak** [comment] 2019-03-14 07:28
Sure, go ahead!

**Closed as completed** 2019-03-14 07:35 UTC
